apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: llama.cpp
  annotations:
    scenarios.ai.sap.com/description: "Run a llama.cpp server on SAP AI Core"
    scenarios.ai.sap.com/name: "llama.cpp"
    executables.ai.sap.com/description: "Run a llama.cpp server on SAP AI Core"
    executables.ai.sap.com/name: "llama.cpp"
  labels:
    scenarios.ai.sap.com/id: "llama.cpp"
    ai.sap.com/version: "0.0.1"
spec:
  inputs:
    parameters:
      - name: modelName # placeholder name
        default: "mixtral" 
        type: string # required for every parameters
        description: "Model Name to be used in SAP Generative AI Hub SDK. Ensure an identical value as alias parameter"
      - name: resourcePlan
        type: "string"
        default: "infer.s"
        description: "Resource Plan of SAP AI Core. Supported: infer.s, infer.m, infer.l, train.l"
      - name: modelDownloadUrl # placeholder name
        default: "https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/resolve/main/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf" 
        type: string # required for every parameters
        description: "URL to download UUGF with wget. e.g. https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/resolve/main/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf"
      - name: modelFileName # placeholder name
        default: "mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf" 
        type: string # required for every parameters
        description: "The model file name"
      - name: alias # placeholder name
        default: "mixtral" 
        type: string # required for every parameters
        description: "The model alias to be used in inference"
      - name: threads # placeholder name
        default: "3" 
        type: string # required for every parameters
        description: "The number of threads to be used in compute"
      - name: ctxSize # placeholder name
        default: "4098" 
        type: string # required for every parameters
        description: "Size of the prompt context "
      - name: ngl # placeholder name
        default: "33" 
        type: string # required for every parameters
        description: "Number of layers to be offloaded into GPU VRAM"
      - name: enableEmbeddings # placeholder name
        default: "true" 
        type: string # required for every parameters
        description: "Enable embedding vector output.Valid values as 'true' or 'false'"
    artifacts: 
      - name: customModel # Only used for hosting custom model or fine-tuning model in object store.
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: "{{inputs.parameters.resourcePlan}}"
    spec: |
      predictor:
        imagePullSecrets:
        - name: docker-secret
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/unnatihasija/llama.cpp-server:ai-core
          ports:
            - containerPort: 8080
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -e && echo "-------------Starting llama.cpp Server--------------" 
              && wget -P /models -tries=10 {{inputs.parameters.modelDownloadUrl}}
              && /server 
              --model /models/{{inputs.parameters.modelFileName}}
              --alias {{inputs.parameters.alias}}
              --threads {{inputs.parameters.threads}}
              --ctx-size {{inputs.parameters.ctxSize}}
              --n-gpu-layers {{inputs.parameters.ngl}}
              --embeddings
          env:
            - name: STORAGE_URI #uncommented these two lines for custom model or fine-tuning.
              value: "{{inputs.artifacts.customModel}}"
            - name: MODEL_DOWNLOAD_URL
              value: "{{inputs.parameters.modelDownloadUrl}}" 
            - name: MODEL_FILE_NAME
              value: "{{inputs.parameters.modelFileName}}" 
            - name: ALIAS
              value: "{{inputs.parameters.alias}}" 
            - name: THREADS
              value: "{{inputs.parameters.threads}}" 
            - name: CTX_SIZE
              value: "{{inputs.parameters.ctxSize}}" 
            - name: N_GPU_LAYERS
              value: "{{inputs.parameters.ngl}}"
            - name: ENABLE_EMBEDDINGS
              value: "{{inputs.parameters.enableEmbeddings}}" 
